### ISSUE TITLE
Question: why use napybara?

### ISSUE THREAD

**Issue by rstacruz** [gsmendoza/napybara#1]
From the readme:

``` rb
messages_page.form.message_row.text_field.node.set 'Hello World!'
messages_page.form.submit!
```

This can already be achieved in Capybara:

``` rb
within 'form .message_row' do
  fill_in '#message', with: 'Hello World!'
end
```

**Comment by gsmendoza** [comment]
Off the top of my head,
1. It provides a more object-oriented way to write test helpers. Ever been bothered by having a ton of test helpers that do not have a consistent API? - `sign_in_as(user, admin: true)`, `fill_in_message(message)`, `submit_form(name: 'test', age: 10)`... 
2. It allows you to form abstractions of pages when testing. In the above example, I can think of the messages page as having a form which has a message text field.
3. It's easier to debug. If the `message_row` is buggy, I can just `#inspect` it. Also, with the `within` example, if the `fill_in` statement is buggy, I'd have to set the breakpoint in the `within` block so that I wouldn't have to type `form .message_row`. That can sometimes be annoying.

Do check out page objects for more info :)

**Comment by rstacruz** [comment]
I haven't used napybara but it looks like aliases for certain finders, ie:

``` rb
let(:messages_page) do
  Napybara::Element.new(self) do |page|
    page.finder :form, 'form.new-message' do |form|
      form.finder :message_row, '.message-row' do |row|
        row.finder :text_field, 'input[type=text]'
      end
    end
  end
end

messages_page.form.message_row.text_field #=> "form.new-message .message-now input[type=text]"
```

isnt this something you can write as:

``` rb
form = 'form.new-message'
message_row = '.message-row'
text_field = 'input[type="text"]'

el = page.find(form).find(message_row).find(text_field)
el.value
el.[:type] == 'text'
```

or to make it more meta-programming-like:

``` rb
module MessagesPage
  def form
    el 'form.new-message'
  end

  def message_row
    el ".message-row"
  end

  def el(selector)
    find(selector).tap { |element| element.extend self }
  end
end

page.extend MessagesPage

page.form.message_row
# => page.find('form.new-message').find('.message_row')
```

**Comment by gsmendoza** [comment]
That's very neat :) I guess the only thing that bothers me about `extend` is that it's adding methods to the Capybara object. If Capybara adds new methods to their API, that may cause the custom helpers to break. Probably not that hard to fix though.

I started off with Page classes like in your example but chose to standardize them in Napybara because I needed more fancy features like [checking if an element exists](https://github.com/gsmendoza/napybara/#checking-if-an-element-exists) and [finding all elements matching a selector](https://github.com/gsmendoza/napybara/#finding-all-elements-matching-a-selector). But if you're able to implement the README with just extending Capybara objects, let me know. Your solution's probably going to be more lightweight than Napybara :)
